spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libcat?useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
