spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libcat?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
