spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/libcat?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
